### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by liux893** [Alphakyl/OctomapMerge#1]
After I ran your code, the following problem appeared, how can I solve it?

[FATAL] [1619011175.540722652]: Error opening file: /media/kyle/45bfdd4b-6c7c-4d6a-a09d-21fbe576aa92/niosh/TUNNEL_DEPLOYMENT_3/H02/outputs_2019-08-20-14-02-24_0.bag
[FATAL] [1619011175.540722622]: Error opening file: /media/kyle/45bfdd4b-6c7c-4d6a-a09d-21fbe576aa92/niosh/TUNNEL_DEPLOYMENT_3/H03/outputs_2019-08-20-14-09-15_0.bag
[player1-5] process has died [pid 28120, exit code 1, cmd /opt/ros/noetic/lib/rosbag/play --clock /media/kyle/45bfdd4b-6c7c-4d6a-a09d-21fbe576aa92/niosh/TUNNEL_DEPLOYMENT_3/H02/outputs_2019-08-20-14-02-24_0.bag /media/kyle/45bfdd4b-6c7c-4d6a-a09d-21fbe576aa92/niosh/TUNNEL_DEPLOYMENT_3/H02/outputs_2019-08-20-14-22-24_1.bag __name:=player1 __log:=/home/zz/.ros/log/370e980c-a2a4-11eb-a71a-8d5fada985de/player1-5.log].
log file: /home/zz/.ros/log/370e980c-a2a4-11eb-a71a-8d5fada985de/player1-5*.log
[player2-4] process has died [pid 28115, exit code 1, cmd /opt/ros/noetic/lib/rosbag/play --clock /media/kyle/45bfdd4b-6c7c-4d6a-a09d-21fbe576aa92/niosh/TUNNEL_DEPLOYMENT_3/H03/outputs_2019-08-20-14-09-15_0.bag /media/kyle/45bfdd4b-6c7c-4d6a-a09d-21fbe576aa92/niosh/TUNNEL_DEPLOYMENT_3/H03/outputs_2019-08-20-14-29-15_1.bag __name:=player2 __log:=/home/zz/.ros/log/370e980c-a2a4-11eb-a71a-8d5fada985de/player2-4.log].
log file: /home/zz/.ros/log/370e980c-a2a4-11eb-a71a-8d5fada985de/player2-4*.log

**Comment by Alphakyl** [comment]
The launch file has paths to specific bag files that I was using to show the software working for a demonstration. You would need to add/edit arguments for paths to ROS bags containing octomaps that you wish to merge. Specifically look at lines 12-21 in /launch/merge.launch and add your own relevant paths and bag titles.

**Comment by liux893** [comment]
Thank you for your reply! Can you tell me what types of files are stored in ROS bags?

**Comment by liux893** [comment]
In ros bags, is the octree map stored in the map data? Or is it a point cloud map?
